services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.7
    ports:
      - '8000:8080'
    env_file:
      - ./envs/keycloak.env
    command: start-dev
    volumes:
      - keycloak-data:/opt/keycloak/data/

  postgres:
    image: postgres:16
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - ./envs/postgres.env
  
  rabbitmq:
    rabbitmq:
    image: rabbitmq:4.0-management
    ports:
      - 5672:5672
    env_file:
      - ./envs/prod/rabbitmq.env

volumes:
  keycloak-data:
  postgres-data: