services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.7
    ports:
      - '8000:8080'
    env_file:
      - ./envs/keycloak.env
    command: start-dev
    volumes:
      - keycloak-data:/opt/keycloak/data/

  postgres:
    image: postgres:16
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - ./envs/postgres.env

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    networks:
      - aw-network
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - aw-network
    links:
      - postgres
    env_file:
      - ./envs/grafana.env
    depends_on:
      - prometheus
      - postgres

  sisconf:
    build:
      context: ./
      dockerfile: ./compose/local/Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - ./target:/workspace/app/target # For live reloading
      - ./src:/workspace/app/src # For live reloading
      - ./pom.xml:/workspace/app/pom.xml # For efficient build
      - mvn-cache:/root/.m2 # For caching mvn dependencies
    env_file:
      - ./envs/spring.env
    depends_on:
      - postgres
      - keycloak

networks:
  aw-network:
    driver: bridge

volumes:
  keycloak-data:
  postgres-data:
  mvn-cache:
  prometheus-data:
  grafana-data: