services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.7
    ports:
      - '8000:8080'
    env_file:
      - ./envs/keycloak.env
    command: start-dev
    volumes:
      - keycloak-data:/opt/keycloak/data/

  postgres:
    image: postgres:16
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - ./envs/postgres.env

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    links:
      - postgres
    env_file:
      - ./envs/grafana.env
    depends_on:
      - prometheus
      - postgres

  postgresql-exporter:
    image: prometheuscommunity/postgres-exporter
    container_name: postgres-exporter
    ports:
      - "9187:9187"
    env_file:
      - ./envs/postgres.env
    depends_on:
      - postgres

volumes:
  keycloak-data:
  postgres-data:
  mvn-cache:
  prometheus-data:
  grafana-data:
  postgresql-exporter: