services:
  postgres:
    image: postgres:16
    volumes:
      - postgres-prod-data:/var/lib/postgresql/data
    env_file:
      - ./envs/prod/postgres.env

  rabbitmq:
    image: rabbitmq:4.0-management
    ports:
      - 5672:5672
    env_file:
      - ./envs/prod/rabbitmq.env

  sisconf:
    build:
      context: ./
      dockerfile: ./compose/prod/Dockerfile
    ports:
      - 8080:8080
    env_file:
      - ./envs/prod/spring.env
  
  nginx:
    image: nginx:latest
    depends_on:
      - sisconf
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: always

volumes:
  postgres-prod-data: