CREATE TABLE IF NOT EXISTS stock(
    id SERIAL PRIMARY KEY,
    entrepreneur_id INT NOT NULL REFERENCES entrepreneur ON DELETE CASCADE UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);