CREATE TABLE IF NOT EXISTS stock(
    id SERIAL PRIMARY KEY,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS stock_food(
    food_id INT REFERENCES food ON DELETE CASCADE,
    stock_id INT REFERENCES stock ON DELETE CASCADE,
    quantity INT NOT NULL DEFAULT 1,
    CONSTRAINT stock_food_pk PRIMARY KEY (food_id, stock_id)
);

ALTER TABLE food
ALTER COLUMN name SET NOT NULL,
ALTER COLUMN name SET DEFAULT '';

ALTER TABLE food
ADD CONSTRAINT food_name_unique
UNIQUE(name);

ALTER TABLE food
ALTER COLUMN category SET NOT NULL,
ALTER COLUMN category SET DEFAULT 'FRUIT';

ALTER TABLE food
ALTER COLUMN unit_price SET NOT NULL,
ALTER COLUMN unit_price SET DEFAULT 0;

