CREATE TABLE IF NOT EXISTS country_state(
    id SERIAL PRIMARY KEY,
    fullname VARCHAR(255) NOT NULL,
    abbreviation CHAR(2) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS city(
   id SERIAL PRIMARY KEY,
   name VARCHAR(255) NOT NULL,
   country_state_id INT NOT NULL REFERENCES country_state ON DELETE RESTRICT,
   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS address(
    id SERIAL PRIMARY KEY,
    street VARCHAR(128) NOT NULL,
    zip_code VARCHAR(9) NOT NULL,
    neighbourhood VARCHAR(128) NOT NULL,
    number SMALLINT NOT NULL,
    city_id INT NOT NULL REFERENCES city ON DELETE RESTRICT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS person(
    id SERIAL PRIMARY KEY,
    keycloak_id VARCHAR(36) NOT NULL UNIQUE,
    cpf VARCHAR(14) NOT NULL UNIQUE,
    cnpj VARCHAR(15) UNIQUE,
    email VARCHAR(128) NOT NULL UNIQUE,
    phone VARCHAR(15) NOT NULL,
    address_id INT NOT NULL REFERENCES address ON DELETE RESTRICT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS customer(
    id SERIAL PRIMARY KEY,
    category VARCHAR(12) NOT NULL,
    person_id INT NOT NULL REFERENCES person ON DELETE RESTRICT UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS entrepreneur(
    id SERIAL PRIMARY KEY,
    business_name VARCHAR(128) NOT NULL,
    person_id INT NOT NULL REFERENCES person ON DELETE RESTRICT UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);