name: CI

on: [pull_request, push]

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # Use Temurin (Adoptium) JDK
          java-version: '21' # Use Java 17 (or your desired version)
      
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-
      
      - name: Build application
        run: ./mvnw clean package -DskipTests
      
      - name: Run tests
        run: ./mvnw test
