name: CI

on: [pull_request, push]

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: JDK Setup
        uses: actions/setup-java@v4
        with:
          java-version: "21 "
          distribution: "temurin"
          cache: maven

      - name: Application building
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./docker-compose.yml"

      - name: Application testing
        run: |
          docker compose exec sisconf-backend-sisconf-1 mvn test
