name: CI

on: [pull_request, push]

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: JDK Setup
        uses: actions/setup-java@v4
        with:
          java-version: "21 "
          distribution: "temurin"
          cache: maven

      - name: Application testing
        run: mvn -B test --file pom.xml

      - name: Application building
        run: |
          mvn clean
          mvn -B package --file pom.xml
