name: CI/CD

on: [pull_request, push]

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    env:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${{secrets.KC_BOOTSTRAP_ADMIN_USERNAME}}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${{secrets.KC_BOOTSTRAP_ADMIN_PASSWORD}}
      POSTGRES_USER: ${{secrets.POSTGRES_USER}}
      POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
      POSTGRES_DB: ${{secrets.POSTGRES_DB}}
      KEYCLOAK_SERVER_URL: ${{secrets.KEYCLOAK_SERVER_URL}}
      KEYCLOAK_REALM: ${{secrets.KEYCLOAK_REALM}}
      KEYCLOAK_CLIENT_ID: ${{secrets.KEYCLOAK_CLIENT_ID}}
      KEYCLOAK_CLIENT_SECRET: ${{secrets.KEYCLOAK_CLIENT_SECRET}}
      SPRING_APPLICATION_NAME: ${{secrets.SPRING_APPLICATION_NAME}}
      SPRING_DATA_SOURCE_URL: ${{secrets.SPRING_DATA_SOURCE_URL}}
      SPRING_DATA_SOURCE_USERNAME: ${{secrets.SPRING_DATA_SOURCE_USERNAME}}
      SPRING_DATA_SOURCE_PASSWORD: ${{secrets.SPRING_DATA_SOURCE_PASSWORD}}
      SPRING_DATA_SOURCE_DRIVER_CLASS_NAME: ${{secrets.SPRING_DATA_SOURCE_DRIVER_CLASS_NAME}}
      SPRING_JPA_HIBERNATE_DIALECT: ${{secrets.SPRING_JPA_HIBERNATE_DIALECT}}
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${{secrets.SPRING_JPA_HIBERNATE_DDL_AUTO}}
      RABBIT_MQ_ORDERS_GROUP_SHEET_QUEUE_NAME: ${{secrets.RABBIT_MQ_ORDERS_GROUP_SHEET_QUEUE_NAME}}
      RABBIT_MQ_HOSTNAME: ${{secrets.RABBIT_MQ_HOSTNAME}}
      RABBIT_MQ_PORT: ${{secrets.RABBIT_MQ_PORT}}
      RABBIT_MQ_USERNAME: ${{secrets.RABBIT_MQ_USERNAME}}
      RABBIT_MQ_PASSWORD: ${{secrets.RABBIT_MQ_PASSWORD}}
      AMAZON_S3_ACCESS_KEY_ID: ${{secrets.AMAZON_S3_ACCESS_KEY_ID}}
      AMAZON_S3_BUCKET_NAME: ${{secrets.AMAZON_S3_BUCKET_NAME}}
      AMAZON_S3_BUCKET_REGION: ${{secrets.AMAZON_S3_BUCKET_REGION}}
      AMAZON_S3_SECRET_ACCESS_KEY: ${{secrets.AMAZON_S3_SECRET_ACCESS_KEY}}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Application building
        run: docker compose -f docker-compose.yml up -d

      - name: Application testing
        run: |
          docker exec sisconf-prod /workspace/app/mvnw test

      - name: Post Application Building and Testing
        run: |
          docker compose -f docker-compose.yml down

  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/main'
    needs: [continuous-integration]
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
        run: |
          echo "$PRIVATE_KEY" > sisconf-backend-spring.pem && chmod 600 sisconf-backend-spring.pem
          ssh -o StrictHostKeyChecking=no -i sisconf-backend-spring.pem ${USER}@${HOST} << 'EOF'
          BRANCH=${{ github.ref_name }}

          if [ -d "sisconf-backend" ]; then
            cd sisconf-backend
            sudo docker compose -f docker-compose-prod.yml down
          fi

          sudo rm -rf sisconf-backend
          git clone --branch ${BRANCH} --single-branch https://github.com/SISCONF/sisconf-backend.git

          cd sisconf-backend
          ls
          cd ./envs
          mkdir prod
          cd prod

          touch spring.env
          cat ~/spring.env > spring.env
          touch postgres.env
          cat ~/postgres.env > postgres.env
          touch rabbitmq.env
          cat ~/rabbitmq.env > rabbitmq.env

          cd ~/sisconf-backend
          mkdir nginx
          cd nginx
          touch default.conf
          cat ~/nginx.conf > default.conf

          cd ~/sisconf-backend
          sudo docker compose -f docker-compose-prod.yml up -d
          EOF
